### ISSUE TITLE
theming: set global CSS properties

### ISSUE THREAD

**Issue by seb-pereira** [ibm-js/delite#128]
In d1 dojox/mobile, global CSS theme properties were dynamically set using `mobile`  and `mblBackground` classes. Example on iOS theme:

``` css
/* class mobile is set on html element */
html.mobile, .mobile body {
    margin: 0;
    padding: 0;
    width: 100%;
}
.mobile body {
    font-family: Helvetica;
    font-size: 17px;
    overflow-x: hidden;
}
/* class mblBackground is set on body element */
.mblBackground {
    background-color: #C5CCD3;
}
```

In delite we need a mechanism to set global theme properties without having the application to explicitly set one or more classes on html and/or body elements.
