### ISSUE TITLE
[themes] Adding a `d-hidden` and `d-invisible` class to global.less

### ISSUE THREAD

**Issue by tkrugg** [ibm-js/delite#197]
Theses two classes would be defined as follow:

``` css
.d-hidden {display: none}
.d-invisible {visibility: hidden}
```
